theme: jekyll-theme-cayman
# Site settings
title: 大树老周的博客    				  	#你博客的标题
SEOTitle: 大树老周的博客  | cxzzx007 Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: zhouzx_work@foxmail.com	
description: "Study And Research"  			 #网站介绍
keyword: "Blog" #关键词
url: "https://cxzzx007.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "Study"
